esphome:
  name: yandex-station-mini
  friendly_name: yandex-station-mini
  comment: "Яндекс Станция Мини"

esp8266:
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: on

logger:

api:
  reboot_timeout: 0s

ota:
  password: "esphome"

switch:
  - platform: gpio
    pin: GPIO5
    name: Analog Output
